sbx_virus_id:
  blast_db: ''
  blastx_threads: 4
  bowtie2_build_threads: 4
  cenote_taker2_db: ''
  virsorter_db: ''
  include_phages: False
  use_spades: False # Default: Megahit
  use_virsorter: False # Default: Cenote-Taker2