name: Tests

on:
    pull_request:
      branches:
        - main
    push:
      branches:
        - main

jobs:
    run-tests:
        uses: ./.github/workflows/tests.yml
        secrets: inherit
    